import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'auth.signInButton': 'Sign In',
      'auth.loginFormField': 'Login',
      'auth.passwordFormField': 'Password',
      'auth.nameFormField': 'Name',
      'auth.signInErrorTitle': 'Sign In Error',
      'auth.signInError': 'Login failed: email or password incorrect.',
      'auth.resetPasswordLabelButton': 'Forgot password?',
      'auth.signUpLabelButton': 'Create an Account',
      'auth.signUpErrorTitle': 'Sign Up Failed.',
      'auth.signUpError': 'There was a problem signing up.  Please try again later.',
      'auth.signInLabelButton': 'Have an Account? Sign In.',
      'auth.resetPasswordNoticeTitle': 'Password Reset Email Sent',
      'auth.resetPasswordNotice': 'Check your email and follow the instructions to reset your password.',
      'auth.resetPasswordFailed': 'Password Reset Email Failed',
      'auth.signInonResetPasswordLabelButton': 'Sign In',
      'auth.updateUser': 'Update Profile',
      'auth.updateUserSuccessNoticeTitle': 'User Updated',
      'auth.updateUserSuccessNotice': 'User information successfully updated.',
      'auth.updateUserEmailInUse': 'That email address already has an account.',
      'auth.updateUserFailNotice': 'Failed to update user',
      'auth.enterPassword': 'Enter your password',
      'auth.cancel': 'Cancel',
      'auth.submit': 'Submit',
      'auth.changePasswordLabelButton': 'Change Password',
      'auth.resetPasswordTitle': 'Reset Password',
      'auth.updateProfileTitle': 'Update Profile',
      'auth.wrongPasswordNoticeTitle': 'Login Failed',
      'auth.wrongPasswordNotice': 'The password does not match our records.',
      'auth.unknownError': 'Unknown Error',
      'settings.title': 'Settings',
      'settings.language': 'Language',
      'settings.theme': 'Theme',
      'settings.signOut': 'Sign Out',
      'settings.dark': 'Dark',
      'settings.light': 'Light',
      'settings.system': 'System',
      'settings.updateProfile': 'Update Profile',
      'home.title': 'Home',
      'home.nameLabel': 'Name',
      'home.uidLabel': 'UID',
      'home.emailLabel': 'Email',
      'home.adminUserLabel': 'Admin User',
      'app.title': 'Flutter Starter Project',
      'validator.email': 'Please enter a valid email address.',
      'validator.password': 'Password must be at least 6 characters.',
      'validator.name': 'Please enter a name.',
      'validator.number': 'Please enter a number.',
      'validator.notEmpty': 'This is a required field.',
      'validator.amount': 'Please enter a number i.e. 250 - no dollar symbol and no cents',
    },
    'pl': {
      'common.save': 'Zapisz',
      'common.errorOccurred': 'Wystąpił błąd',
      'common.waypoint': 'Punkt trasy',
      'common.address': 'Adres',
      'common.intercom': 'Kod do domofonu',
      'common.phone': 'Numer telefonu',
      'common.note': 'Notatka',
      'common.quantity': 'Ilość paczek',
      'common.content': 'Zawartość',
      'common.driverNote': 'Notatka kierowcy',
      'common.yes': 'Tak',
      'common.no': 'Nie',
      'auth.signInButton': 'Zaloguj się',
      'auth.loginFormField': 'Login',
      'auth.passwordFormField': 'Hasło',
      'auth.nameFormField': 'Nom',
      'auth.signInErrorTitle': 'Błąd uwierzytelniania',
      'auth.signInError': 'Błędny login lub hasło.',
      'auth.resetPasswordLabelButton': 'Mot de passe oublié?',
      'auth.signUpLabelButton': 'Créer un compte',
      'auth.signUpErrorTitle': 'Échec de l\'inscription.',
      'auth.signUpError': 'Il y avait un problème de signer. Veuillez réessayer plus tard.',
      'auth.signInLabelButton': 'Avoir un compte? S\'identifier.',
      'auth.resetPasswordNoticeTitle': 'Réinitialiser le mot de passe e-mail envoyé',
      'auth.resetPasswordNotice': 'Vérifiez votre e-mail et suivez les instructions pour réinitialiser votre mot de passe.',
      'auth.resetPasswordFailed': 'Réinitialiser le mot de passe Email Échec',
      'auth.signInonResetPasswordLabelButton': 'S\'identifier',
      'auth.updateUser': 'Mettre à jour le profil',
      'auth.updateUserSuccessNoticeTitle': 'Mise à jour l\'utilisateur',
      'auth.updateUserSuccessNotice': 'Informations sur l\'utilisateur mis à jour avec succès.',
      'auth.updateUserEmailInUse': 'Cette adresse e-mail a déjà un compte.',
      'auth.updateUserFailNotice': 'Impossible de mettre à jour l\'utilisateur',
      'auth.enterPassword': 'Tapez votre mot de passe',
      'auth.cancel': 'Annuler',
      'auth.submit': 'Soumettre',
      'auth.changePasswordLabelButton': 'Changer le mot de passe',
      'auth.resetPasswordTitle': 'réinitialiser le mot de passe',
      'auth.updateProfileTitle': 'Mettre à jour le profil',
      'auth.wrongPasswordNoticeTitle': 'Błąd uwierzytelniania',
      'auth.wrongPasswordNotice': 'Le mot de passe ne correspond pas à nos dossiers.',
      'auth.unknownError': 'Erreur inconnue',
      'settings.title': 'Ustawienia',
      'settings.language': 'Język',
      'settings.theme': 'Motyw',
      'settings.signOut': 'Wyloguj się',
      'settings.dark': 'Dark',
      'settings.light': 'Light',
      'settings.system': 'System',
      'settings.updateProfile': 'Mettre à jour le profil',
      'home.title': 'Strona główna',
      'home.nameLabel': 'Użytkownik',
      'home.uidLabel': 'UID',
      'home.emailLabel': 'E-mail',
      'home.adminUserLabel': 'utilisateur admin',
      'app.title': 'Flutter projet de démarrage',
      'routes.title': 'Trasy',
      'routes.routeDownloadedTitle': 'Pobrano trasę',
      'routes.routeDownloaded': 'Dane trasy zostały pobrane pomyślnie.',
      'currentRoute.title': 'Aktualna trasa',
      'currentRoute.delivered': 'Dostarczone',
      'currentRoute.undelivered': 'Niedostarczone',
      'currentRoute.updateStatusErrorTitle': 'Nie można zmienić statusu dostarczenia',
      'currentRoute.statusUpdatedTitle': 'Zmiana statusu',
      'currentRoute.statusUpdated': 'Zapisano zmiane statusu dostarczenia.',
      'about.title': 'O aplikacji',
      'map.title': 'Mapa',
      'waypoint.driverNote': 'Notatka kierowcy',
      'waypoint.noteEdit': 'Edycja notatki',
      'waypoint.photoUploaded': 'Wgrano zdjęcie',
      'waypoint.deliveryProblem': 'Problem z dostarczeniem',
      'waypoint.editDriverNote': 'Edytuj notatkę kierowcy',
      'waypoint.navigate': 'Nawigacja',
      'waypoint.call': 'Zadzwoń',
      'waypoint.sendSMS': 'Wyślij SMS',
      'waypoint.takePhoto': 'Zrób zdjęcie',
      'validator.email': 'S\'il vous plaît, mettez une adresse email valide.',
      'validator.password': 'Hasło musi zawierać conajmniej 6 znaków.',
      'validator.login': 'Wprowadź prawidłowy login.',
      'validator.name': 'S\'il vous plaît entrer un nom.',
      'validator.number': 'S\'il vous plaît entrer un numéro.',
      'validator.notEmpty': 'Ceci est un champ obligatoire.',
      'validator.amount': 'S\'il vous plaît entrer un numéro à savoir 250 - aucun symbole du dollar et pas cents',
    }
  };
}
